CREATE DATABASE citiesData;
use citiesData;

CREATE TABLE IF NOT EXISTS tblCitiesImport (
    `id` int AUTO_INCREMENT,
    `fldName` VARCHAR(30) CHARACTER SET utf8,
    `fldYear` INT,
    `fldAge` INT,
    `fldMovie` VARCHAR(30) CHARACTER SET utf8,
    `fldExtra` VARCHAR(30) CHARACTER SET utf8,
    PRIMARY KEY (`id`)
);
INSERT INTO tblCitiesImport (fldName,fldYear,fldAge,fldMovie,fldExtra) VALUES
    (' "Emil Jannings"', 1928, 44, ' "The Last Command',' The Way of All Flesh'),
    (' "Warner Baxter"', 1929, 41, ' "In Old Arizona"',NULL),
    (' "George Arliss"', 1930, 62,' "Disraeli"',NULL),
    (' "Lionel Barrymore"', 1931, 53,' "A Free Soul"',NULL),
    (' "Wallace Beery"', 1932, 47,' "The Champ"',NULL),
    (' "Fredric March"', 1933, 35,' "Dr. Jekyll and Mr. Hyde"',NULL),
    (' "Charles Laughton"', 1934, 34,' "The Private Life of Henry VIII"',NULL),
    (' "Clark Gable"', 1935, 34,' "It Happened One Night"',NULL),
    (' "Victor McLaglen"', 1936, 49,' "The Informer"	',NULL),
    (' "Paul Muni"', 1937, 41,' "The Story of Louis Pasteur"	',NULL),
    (' "Spencer Tracy"', 1938, 37,' "Captains Courageous"',NULL),
    (' "Spencer Tracy"', 1939, 38,' "Boys Town"',NULL),
    (' "Robert Donat"', 1940, 34,' "Goodbye',' Mr. Chips"	'),
    (' "James Stewart"', 1941, 32,' "The Philadelphia Story"',NULL),
    (' "Gary Cooper"', 1942, 40,' "Sergeant York"',NULL),
    (' "James Cagney"', 1943, 43,' "Yankee Doodle Dandy"	',NULL),
    (' "Paul Lukas"', 1944, 48,' "Watch on the Rhine"	',NULL),
    (' "Bing Crosby"', 1945, 41,' "Going My Way"',NULL),
    (' "Ray Milland"', 1946, 39,' "The Lost Weekend" 	',NULL),
    (' "Fredric March"', 1947, 49,' "The Best Years of Our Lives"',NULL),
    (' "Ronald Colman"', 1948, 57,' "A Double Life"',NULL),
    (' "Laurence Olivier"', 1949, 41,' "Hamlet"',NULL),
    (' "Broderick Crawford"', 1950, 38,' "All the King''s Men"',NULL),
    (' "José Ferrer"', 1951, 39,' "Cyrano de Bergerac"',NULL),
    (' "Humphrey Bogart"', 1952, 52,' "The African Queen"',NULL),
    (' "Gary Cooper"', 1953, 51,' "High Noon"',NULL),
    (' "William Holden"', 1954, 35,' "Stalag 17"',NULL),
    (' "Marlon Brando"', 1955, 30,' "On the Waterfront"',NULL),
    (' "Ernest Borgnine"', 1956, 39,' "Marty"',NULL),
    (' "Yul Brynner"', 1957, 36,' "The King and I"',NULL),
    (' "Alec Guinness"', 1958, 43,' "The Bridge on the River Kwai"',NULL),
    (' "David Niven"', 1959, 49,' "Separate Tables"',NULL),
    (' "Charlton Heston"', 1960, 36,' "Ben-Hur"',NULL),
    (' "Burt Lancaster"', 1961, 47,' "Elmer Gantry"',NULL),
    (' "Maximilian Schell"', 1962, 31,' "Judgment at Nuremberg"	',NULL),
    (' "Gregory Peck"', 1963, 47,' "To Kill a Mockingbird"',NULL),
    (' "Sidney Poitier"', 1964, 37,' "Lilies of the Field"',NULL),
    (' "Rex Harrison"', 1965, 57,' "My Fair Lady"',NULL),
    (' "Lee Marvin"', 1966, 42,' "Cat Ballou"	',NULL),
    (' "Paul Scofield"', 1967, 45,' "A Man for All Seasons"',NULL),
    (' "Rod Steiger"', 1968, 42,' "In the Heat of the Night"	',NULL),
    (' "Cliff Robertson"', 1969, 45,' "Charly"',NULL),
    (' "John Wayne"', 1970, 62,' "True Grit"',NULL),
    (' "George C. Scott"', 1971, 43,' "Patton"',NULL),
    (' "Gene Hackman"', 1972, 42,' "The French Connection"',NULL),
    (' "Marlon Brando"', 1973, 48,' "The Godfather"',NULL),
    (' "Jack Lemmon"', 1974, 49,' "Save the Tiger"',NULL),
    (' "Art Carney"', 1975, 56,' "Harry and Tonto"',NULL),
    (' "Jack Nicholson"', 1976, 38,' "One Flew Over the Cuckoo''s Nest"',NULL),
    (' "Peter Finch"', 1977, 60,' "Network"',NULL),
    (' "Richard Dreyfuss"', 1978, 30,' "The Goodbye Girl"',NULL),
    (' "Jon Voight"', 1979, 40,' "Coming Home"',NULL),
    (' "Dustin Hoffman"', 1980, 42,' "Kramer vs. Kramer"',NULL),
    (' "Robert De Niro"', 1981, 37,' "Raging Bull"',NULL),
    (' "Henry Fonda"', 1982, 76,' "On Golden Pond"',NULL),
    (' "Ben Kingsley"', 1983, 39,' "Gandhi"',NULL),
    (' "Robert Duvall"',1984, 53,' "Tender Mercies"',NULL),
    (' "F. Murray Abraham"', 1985, 45,' "Amadeus"',NULL),
    (' "William Hurt"', 1986, 36,' "Kiss of the Spider Woman"',NULL),
    (' "Paul Newman"', 1987, 62,' "The Color of Money"',NULL),
    (' "Michael Douglas"', 1988, 43,' "Wall Street"',NULL),
    (' "Dustin Hoffman"', 1989, 51,' "Rain Man"',NULL),
    (' "Daniel Day-Lewis"', 1990, 32,' "My Left Foot"',NULL),
    (' "Jeremy Irons"', 1991, 42,' "Reversal of Fortune"',NULL),
    (' "Anthony Hopkins"', 1992, 54,' "The Silence of the Lambs"',NULL),
    (' "Al Pacino"', 1993, 52,' "Scent of a Woman"',NULL),
    (' "Tom Hanks"', 1994, 37,' "Philadelphia"',NULL),
    (' "Tom Hanks"', 1995, 38,' "Forrest Gump"',NULL),
    (' "Nicolas Cage"', 1996, 32,' "Leaving Las Vegas"',NULL),
    (' "Geoffrey Rush"', 1997, 45,' "Shine"',NULL),
    (' "Jack Nicholson"', 1998, 60,' "As Good as It Gets"',NULL),
    (' "Roberto Benigni"', 1999, 46,' "Life Is Beautiful"',NULL),
    (' "Kevin Spacey"', 2000, 40,' "American Beauty"',NULL),
    (' "Russell Crowe"', 2001, 36,' "Gladiator"',NULL),
    (' "Denzel Washington"', 2002, 47,' "Training Day"	',NULL),
    (' "Adrien Brody"', 2003, 29,' "The Pianist"',NULL),
    (' "Sean Penn"', 2004, 43,' "Mystic River"',NULL),
    (' "Jamie Foxx"', 2005, 37,' "Ray"',NULL),
    (' "Philip Seymour Hoffman"', 2006, 38,' "Capote"',NULL),
    (' "Forest Whitaker"', 2007, 45,' "The Last King of Scotland"	',NULL),
    (' "Daniel Day-Lewis"', 2008, 50,' "There Will Be Blood"',NULL),
    (' "Sean Penn"', 2009, 48,' "Milk"',NULL),
    (' "Jeff Bridges"', 2010, 60, '"Crazy Heart"',NULL),
    (' "Colin Firth"', 2011, 50,' "The King''s Speech"	',NULL),
    (' "Jean Dujardin"', 2012, 39,' "The Artist"',NULL),
    (' "Daniel Day-Lewis"', 2013, 55,' "Lincoln"',NULL),
    (' "Matthew McConaughey"', 2014, 44,' "Dallas Buyers Club"',NULL),
    (' "Eddie Redmayne"', 2015, 33,' "The Theory of Everything"	',NULL),
    (' "Leonardo DiCaprio"', 2016, 41,' "The Revenant"',NULL);